### PR TITLE
Credential values serialization/deserialization

### PR DESCRIPTION
**Pull request by kgoncharov**
**Credential values serialization/deserialization:**

**Description:**
Changes to support json for CredValues related to https://github.com/hyperledger/ursa/pull/210 changes in `ursa`

Summary:

* added toJson/fromJson methods for Credential Values to the header file
* added Golang wrappers for the methods
* updated related test

### CODE REVIEW

**Comment by ryjones** [comment]
@kgoncharov doesn't work on 1.14

**Comment by kgoncharov** [comment]
> @kgoncharov doesn't work on 1.14

looks like it pulls ursa w/o changes made in https://github.com/hyperledger/ursa/pull/210
Could you please restart?
Is it right, that in pipeline ursa is taken from `main` branch?

**Comment by ryjones** [comment]
@kgoncharov It builds from those tags.

**Comment by kgoncharov** [comment]
> @kgoncharov [It builds from main.](https://github.com/hyperledger/ursa-wrapper-go/blob/568671eff5a2e103de16a0ed176b683403bfeb83/.github/workflows/Dockerfile#L46)

As I've checked, the latest image is `sha256:8774267319b0357d1eaf3553d7f44ec84d93e2b715a80bedc5058fe2c69bafe7` which was pushed a year ago.
Looks like, new image hasn't been built due to the changes made by Alex in https://github.com/hyperledger/ursa-wrapper-go/pull/35
He commented out the step with `build-image`, cause it wasn't working.

Could you please manually update the latest image with actual `main` changes and restart pipeline?

 I can't start pipelines myself, since I'm not a maintainer nor a contributor yet and can't quickly fix pipeline.

**Pull request closed without merging**
